### ISSUE TITLE
Automatic rollback

### ISSUE THREAD

**Issue by Zimmi48** [EugeneLoy/coq_jupyter#28]
Thank you for working on providing a Jupyter kernel!

The "rollback" button that you added is very important to make the notebook usable. However, it is my impression that most of the time, remembering to click on this button is actually painful, and we can do better by doing the rollback automatically when needed.

To be more specific, it is my impression that we only (and always) need to rollback in these two cases:
- we insert a cell in the middle of the notebook, and we want to evaluate it (in the context);
- we modify the content of a cell, and we re-evaluate it.

There is a third case that can happen in CoqIDE / Proof General and is made unnecessary by the use of Jupyter: rolling back to replay the proof. Thanks to the Jupyter interface, all the data is already there, and we don't need to replay the proof to see what happened. Therefore, it seems to me that Jupyter provides a much improved interface for teaching Coq and documenting / sharing proofs with others.

I have tried to find how to implement this, by reusing your rollback code, but it seems to me that the `do_execute` method doesn't tell which cell is the code attached to, and then it is impossible to rollback this cell (and the following ones) before executing the code without going lower-level. If so, maybe it is possible to inspire from the code in https://github.com/stitchfix/nodebook...

**Comment by EugeneLoy** [comment]
Hi,
Thank you for your feedback! I agree that adding automatic rollbacks in one form or another would be a great improvement. Not quite sure what is the best way to handle this yet.

Talking about the 1st case, it looks like in most situations it can be handled by default "restart kernel and run all cells" command. Anyway, I think 2nd case is much more common and it's implementation will determine whether or not there is something that needs to be done here, so, let's focus on that for now.

I do see that 2nd case needs to be addressed. Rolling back cell using button (or shortcut) and then running updated cell is kind of cumbersome, yet this seem to be rather common use case. At this point I see multiple ways to handle this, each with its own pros and cons.

**Option 1.** We could enforce cell order, somewhat similar to Nodebook extension you have mentioned and, maybe, leveraging `comm`s instead of `do_execute` to track cell. The main problem here is that, conceptually, typical jupyther notebook (for example for python) is more like collection of code cells that can be run in arbitrary order interactively (which makes jupyter notebook a better interface for REPL, or `coqtop` in our case), rather than something that evaluates some pieces of code step-by-step (like CoqIde does). I am not sure that it is a good idea to step aside from default jupyter notebook model. Surely, enforced order model would be a bit more familiar to typical CoqIde user, however, at the same time, it would be a bit alien for typical jupyter notebook user.

**Option 2.** We could add new "Re-Run" command (button+shortcut) that rolls back current cell and evals updated code. This command can be made to run code from cell in normal way if cell was not run before (for convenience). This can be implemented using `comm`s, similar to "Rollback cell" command. By adding new command we'll preserve default jupyter notebook behavior while providing coq-specific convenience. Drawback is that there will be extra command in addition to default "Run" command.

**Option 3.** Same as option 2 but replace default "Run" command with "Re-Run" behavior described above. Drawback here is that this changes default jupyter conventions (similar to option 1) and that this implementation will probably require moderate use of client-side jupyter api (which is not stable according to jupyter docs). BTW, the last drawback will probably be even more severe for option 1.

At this point option 2 makes most sense to me, however, I might be missing something. What do you think?

**Comment by Zimmi48** [comment]
Thanks for your reply!

>Talking about the 1st case, it looks like in most situations it can be handled by default "restart kernel and run all cells" command.

That's the *hard* solution (and the only one you have when you want e.g. to check the consistency of a Coq document) but it may not be very nice for users who run computationally intensive proof scripts. Heck, we even have users who defend the nested lemma feature as something critical to their workflow because they can't afford to re-run their proof scripts every time they need to add a new intermediate lemma.

>I am not sure that it is a good idea to step aside from default jupyter notebook model.

It is my opinion that the default Jupyter notebook model is made that way in big part because Python doesn't have native support for rolling back to previous state like Coq does. That being said, one thing that is nice is to be able to skip parts of the document (while still evaluating in order). I think this can and should be preserved for Coq (even if this create a risk for the consistency of the document when there are intermediate commands that affect automatic tactics like `Hint Resolve`).

>Surely, enforced order model would be a bit more familiar to typical CoqIde user, however, at the same time, it would be a bit alien for typical jupyter notebook user.

The typical Jupyter notebook user stumbles upon this weird behavior that when going back and editing the notebook you have to account for the state that was created by the execution of later cells. It is quite weird for students and even more seasoned users have to regularly check the consistency of their document by re-running the whole thing from scratch (which can be a pain when the document is computationally intensive). In Python, one is forced to adopt some practices to avoid consistency issues as much as possible (I personally use "closures" to create variables that are local to a cell, and try to consider as much as possible global variables as immutable which means that the only risk that I still have to look for in a Python notebook of mine would be to depend on a variable which is actually defined after).

My proposal to rollback automatically is what I think is best for the time being, but longer term, the kernel could be made to use a real document protocol, in which case editing a cell might not necessarily require to invalidate all the cells beyond: editing within a Qed proof would only invalidate the cells corresponding to the proof itself).

>At this point option 2 makes most sense to me, however, I might be missing something. What do you think?

Option 2 would already be very good if we can bind the command to an easy to use keybinding. So this seems to be the way to go if it makes the implementation simpler. On the other hand, reusing the default "run" command (option 3) would ensure that the kernel works with alternative Jupyter interfaces as the one provided by Cocalc (at the current time, it doesn't manage to display the Rollback button which makes the kernel unusable there).

**Comment by EugeneLoy** [comment]
> It is my opinion that the default Jupyter notebook model is made that way in big part because Python doesn't have native support for rolling back to previous state like Coq does.

I agree with your point here. I think it is best to move discussion about implementing ordered model into it's own ticket (#30) and figure out what and how it should be implemented there.

> Option 2 would already be very good if we can bind the command to an easy to use keybinding.

Assuming no other extension is installed `Ctrl+Shift+Enter` is free and can be used.

> On the other hand, reusing the default "run" command (option 3) would ensure that the kernel works with alternative Jupyter interfaces

This might not be the case. I have to verify this but overriding default run command might require (ab)using unstable experimental client-side api. In fact, even current ascetic api usage might be the reason why Rollback button doesn't display in Cocalc. Let me investigate this in some depth to decide whether this route is viable.

> at the current time, it doesn't manage to display the Rollback button which makes the kernel unusable there

Will check this out in context of #29

**Comment by EugeneLoy** [comment]
It took me longer than I anticipated but I think I've come up with more or less stable way to implement this.

In the most recent implementation, by default, execution of any code will automatically rollback any code that was executed previously in that cell (plus any code dependent on it).
In addition to rollback button from previous versions I also added "auto rollback" setting.
It both provides means to revert to typical Jupyter cell behavior (no auto rollback) and lets user know that auto rollback is a thing and is used by default.

I'd like to test it for some time, but if no major flaw gets detected I will include this as part of v1.5.0 (will release it sometime this week).

**Comment by Zimmi48** [comment]
Awesome @EugeneLoy! I'll try to test it as well tomorrow.

**Comment by EugeneLoy** [comment]
@Zimmi48 note that this is now in `development` branch and has not been published yet. I am attaching most recent build [here](https://github.com/EugeneLoy/coq_jupyter/files/3007573/coq_jupyter-1.4.1.tar.gz) for now.
Just `pip install coq_jupyter-1.4.1.tar.gz` it to try it out.

**Comment by Zimmi48** [comment]
FTR, after running this command, one still needs to run `python -m coq_jupyter.install` to install the kernel (as documented in the README). I did not manage to change the version of the kernel in the CoCalc instance where I had already installed it, but in a new project, I was able to test it and it worked really well.
Overall, this gives a pretty good experience. I will look into using it more in the future (especially with students -- next year, because my students this year are already well advanced in their course and are now used to other interfaces).

One remark for possible future work is that since you are using the XML protocol, it should be possible (in theory, IIRC) to do partial rollbacks (e.g. within a proof that is ended by a `Qed`) without necessarily rolling back what follows. @gares could say more about this. But this poses problems with how to handle `Qed` so I'm not really sure it's worth to actually look into.

`Check`, `Print` and `About` commands could also be sent as queries, without changing the document, but this would require a bit of parsing, so not necessarily worth looking into either.

**Comment by EugeneLoy** [comment]
> FTR, after running this command, one still needs to run python -m coq_jupyter.install to install the kernel

Yes, you're right, I missed that part.

> I was able to test it and it worked really well.
Overall, this gives a pretty good experience. I will look into using it more in the future

Great!

> One remark for possible future work is that since you are using the XML protocol, it should be possible (in theory, IIRC) to do partial rollbacks (e.g. within a proof that is ended by a Qed) without necessarily rolling back what follows. @gares could say more about this. But this poses problems with how to handle Qed so I'm not really sure it's worth to actually look into

Interesting. I don't think I've stumbled upon this myself though. Could you or @gares give me some starting point I could use to investigate this?

> Check, Print and About commands could also be sent as queries, without changing the document, but this would require a bit of parsing, so not necessarily worth looking into either.

Yes, as long as there are no other needs for it, I'd like to do as less parsing on kernel-side as possible to keep it simple. Plus, I found myself using cell with disabled auto rollback as kind of ad-hod "Query Pane" from CoqIDE, so I don't think changing document on queries is that big of a deal.

**Comment by Zimmi48** [comment]
Very good idea on disabling the option for the "query pane" cell.

I'll let @gares tell more about partial rollbacks if he has time for this.

**Comment by gares** [comment]
About fixing broken proofs: the result of the `edit_at` message signals if the edition is in a script fragment that can be edited without invalidating the rest (typically the text between `Proof` and `Qed`). I tried to look at your code but I could not find where you interpret the answer to the command `edit_at`.

**Comment by gares** [comment]
See the doc of the ML API: https://github.com/coq/coq/blob/master/stm/stm.mli#L128

**Comment by EugeneLoy** [comment]
> I tried to look at your code but I could not find where you interpret the answer to the command edit_at.

Yes, it is not there at the moment. The current implementation only cares whether reply value is "good" or "fail" and doesn't look into details.

> About fixing broken proofs: the result of the edit_at message signals if the edition is in a script fragment that can be edited without invalidating the rest (typically the text between Proof and Qed).

> See the doc of the ML API: https://github.com/coq/coq/blob/master/stm/stm.mli#L128

Thanks, I'll check it out. It looks like the relevant part of xml protocol is documented as second return type here: https://github.com/coq/coq/blob/master/dev/doc/xml-protocol.md#command-editAt

BTW, are partial rollbacks like this are implemented in CoqIDE? Other Coq interfaces?

Anyway, I've created #33 for this.

**Comment by gares** [comment]
CoqIDE supports this feature.

**Comment by EugeneLoy** [comment]
@gares sorry, I can't seem to find a way to use this (in CoqIDE 8.9.0). Can you give me some hint on how can I see it in action?

**Comment by gares** [comment]
https://m.youtube.com/watch?v=OAoVHoeXSgk

**Comment by EugeneLoy** [comment]
Thanks!
