### ISSUE TITLE
Kernel in Cocalc doesn't display the Rollback button

### ISSUE THREAD

**Issue by EugeneLoy** [EugeneLoy/coq_jupyter#29]

**Comment by EugeneLoy** [comment]
To @Zimmi48 and other CoCalc uses.

Unfortunately, by default, CoCalc uses their own implementation of the Jupyter ui that does not support front-end extensions (`kernel.js` that implements rollback-related functionality is bundled with Coq kernel and is kind of front-end extension).

This means that as long as you are using their ui there is no straightforward way to add rollback support. Coq kernel will work but you'll have to fallback to vernacular commands for rollback.

Fortunately, there is a workaround that allows one to use all kernel functionality unrestricted. CoCalc provides "classic" Jupyter interface that does support front-end extensions and works with `coq_jupyter`.

To switch to classic ui you need to go to `File` -> `Switch to Classical Notebook`.

More on classical vs CoCalc notebooks [here](https://doc.cocalc.com/jupyter.html#jupyter-classical-vs-cocalc).

**Comment by Zimmi48** [comment]
Did you try with the `coq_jupyter` kernel? When I did, even the classic UI did not work. But anyway, that's more a bug on them than it is on you.

**Comment by EugeneLoy** [comment]
@Zimmi48 Yes I did. There were some other issues that prevented `coq_jupyter` from working with classic ui. They are fixed now and I can confirm that `coq_jupyter` works with classic ui.

**Comment by Zimmi48** [comment]
Awesome, thanks :tada:
