### ISSUE TITLE
Output correct state labels

### ISSUE THREAD

**Issue by EugeneLoy** [EugeneLoy/coq_jupyter#32]
`In[X]` and `Out[X]` should display actual coqtop state labels.

**Comment by Zimmi48** [comment]
Was this supposed to work in the version of the kernel you shared with me or did you fix it afterwards?

**Comment by EugeneLoy** [comment]
Yes, it was included in the version I shared with you.

**Comment by EugeneLoy** [comment]
**Note 1**: `In[X]` displays state label (tip) just before executing cell code and `Out[Y]` displays state label after code has been executed.

**Note 2**: It looks like CoCalc modern ui does not honor execution counts sent by kernel and uses it's own counters. Classic ui works fine.

**Comment by Zimmi48** [comment]
I was using classic UI, but maybe it's just that Coq's state labels increase even after rolling back. It's just less convenient to the user, but not fundamental.

**Comment by EugeneLoy** [comment]
There is a slight discrepancy between how coqtop and xml protocol handles state id's. As you've mentioned coqtop advances state label when you do rollback with `BackTo N` vernacular to some N+X, while rollback with `EditAt` xml protocol command literally sets state id to N.

Based on my observations, for all practical means, xml protocol state ids can be used instead of coqtop-style labels, so this is what I used here.
