### ISSUE TITLE
Deprecate Python 2 support

### ISSUE THREAD

**Issue by XVilka** [EugeneLoy/coq_jupyter#38]
Python 2 days are gone for good: https://pythonclock.org/

Python 2.7 will not be maintained past 2020.

**Comment by EugeneLoy** [comment]
So far support for 2 was pretty cheap.

I guess it is a good idea to keep it as it is **for now** and, maybe, review/simplify documentation once maintenance of 2.7 actually stops.

Will keep this ticket open for this purpose.

**Comment by EugeneLoy** [comment]
Python 2 build is no longer a thing since v1.6.0 release
