### ISSUE TITLE
Incorrect sentence splitting

### ISSUE THREAD

**Issue by Zimmi48** [EugeneLoy/coq_jupyter#41]
Hi,

I've given my first Coq class with Jupyter today. The students have found out some bugs, so I'm reporting them to you.

This first one is pretty straightforward to understand:

When using a focusing bracket `{` or bullet `-` the following tactic (when it is in the same code cell) gets ignored. I've seen this bug before in other user interfaces. The issue is generally that the user interface splits Coq's input into sentences marked by dots. But `{` / `-` should be their own sentence. See the complete grammar of "undotted" separators here: https://github.com/coq/coq/blob/1c1c04d0e3e02ce461fb953f08e2d8c68e52ee63/ide/coq_lex.mll#L30

(tested with coq_jupyter 1.5.1 and Coq 8.11.0)

**Comment by Zimmi48** [comment]
Note that there is a workaround, which I've advised students to use until the bug is fixed, which is to follow every `-` or `{` with an `idtac.`

**Comment by EugeneLoy** [comment]
@Zimmi48 Hi.

> The issue is generally that the user interface splits Coq's input into sentences marked by dots.

Yes, this is the issue here, thanks for pointing this out.

I'll try to release fix for this sometime tomorrow.

**Comment by EugeneLoy** [comment]
@Zimmi48 This is fixed and included in `v 1.5.2`.

Will move to #42 / #40 next.

**Comment by Zimmi48** [comment]
Thanks for your awesome reactivity!
