### ISSUE TITLE
Add Uninstall Steps to README.md

### ISSUE THREAD

**Issue by ColmBhandal** [EugeneLoy/coq_jupyter#47]
The install steps are given in the README:

```
pip install coq-jupyter
python -m coq_jupyter.install
```

But there doesn't seem to be any uninstall steps. If you just uninstall with Pip, then the Notebook still thinks there's Coq installed (but fails when it tries to access it on the backend), so you end up with a "Coq" option even though there's no backend to execute. I think the solution is to remove from the kernelspec as outlined [here](https://stackoverflow.com/a/42647666/5134722). 

```
jupyter kernelspec uninstall coq
pip uninstall coq-jupyter
```

I can add those steps in a PR if desired.

**Comment by EugeneLoy** [comment]
Thanks for reporting this.
> I think the solution is to remove from the kernelspec as outlined [here](https://stackoverflow.com/a/42647666/5134722).

**Comment by EugeneLoy** [comment]
Thanks for reporting this.

> I think the solution is to remove from the kernelspec as outlined [here](https://stackoverflow.com/a/42647666/5134722).

Yes, this is the proper way to remove kernel.

> I can add those steps in a PR if desired.

PR would be great! If not, I can add this sometime around this weekend.
